Qrcode generator
groakat/orchard-sign pull request #3
Opened 2023-06-14 12:31 UTC by DavidA380

Docker: Added qrcode python module and fix for Inkscape install on MacOS

2023-06-15 12:16 UTC, groakat requested changes

2023-06-15 12:16 UTC, groakat commented on start.sh
> +docker run -it --rm -p 8888:8888 -e GRANT_SUDO=yes -v "${PWD}":/home/jovyan/work orchard
Sorry. We committed this change by accident. Can you please remove the `-e GRANT_SUDO=yes` part? It is saver if the terminal in the notebook does not allow root access as depending how the container is launched, some parts of the host system might be exposed.

2023-06-15 13:04 UTC, DavidA380 commented
Done. Let me know if you want me to push it over.                                                                                                                                                


> On 15 Jun 2023, at 13:16, Peter Rennert ***@***.***> wrote:
> 
> 
> @groakat requested changes on this pull request.
> 
> In start.sh <https://github.com/groakat/orchard-sign/pull/3#discussion_r1230920474>:
> 
> > \ No newline at end of file
> +docker run -it --rm -p 8888:8888 -e GRANT_SUDO=yes -v "${PWD}":/home/jovyan/work orchard
> Sorry. We committed this change by accident. Can you please remove the -e GRANT_SUDO=yes part? It is saver if the terminal in the notebook does not allow root access as depending how the container is launched, some parts of the host system might be exposed.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/groakat/orchard-sign/pull/3#pullrequestreview-1481428213>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AUA62DUZRVM7P2ASUDFMGGDXLL4KFANCNFSM6AAAAAAZGJJDJA>.
> You are receiving this because you authored the thread.
>

2023-06-20 10:05 UTC, groakat commented
I think you still have to push your changes

2023-06-21 11:23 UTC, merged